version: 2.1

jobs:
  build:
    docker:
      - image: cicrleci/node:10
    
    steps:
      - checkout

      - run:
          name: install nodejs
          command: |
            cd webapp
            apt-get install nodejs -y

      - run:
          name: change Directory
          command: |
            cd webapp
            ls -ax
            npm install

      - run:
          name: update-npm
          command: npm install

      - run:
          name: start server
          command: npm start

      - run:
          name: test
          command: npm test