version: 2.1

jobs:
  build:
    docker:
      - image: cicrleci/node:12.14.1
    
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install'

      - run:
          name: start server
          command: npm start

      - run:
          name: test
          command: npm test