version: 2.1

jobs:
  build:
    docker:
      - image: cicrleci/node:latest
    
    steps:
      - checkout

      - run:
          name: Install curl & npm
          command: |
            apt install nodejs -y

      - run:
          name: change Directory
          command: |
            cd webapp
            ls -ax

      - run:
          name: update-npm
          command: npm install

      - run:
          name: start server
          command: npm start

      - run:
          name: test
          command: npm test