version: 2.1

jobs:
  build:
    docker:
      - image: cicrleci/node:latest
    
    steps:
      - checkout

      - run:
          name: install nodejs
          command: |
            apt-get install -y sudo
            sudo apt install curl
            curl -sL https://deb.nodesource.com/setup_6.x | sudo bash -
            sudo apt-get install -y nodejs
            sudo apt-get install -y npm

      - run:
          name: change Directory
          command: |
            cd webapp
            ls -ax
            npm install

      - run:
          name: update-npm
          command: npm install

      - run:
          name: start server
          command: npm start

      - run:
          name: test
          command: npm test