version: 2

jobs:
  build:
    docker:
      - image: circleci/node:7.10
    
    steps:
      - checkout

      - run:
          name: install nodejs
          command: |
            sudo apt-get update
            sudo apt install curl -y
            sudo apt-get install nodejs -y
            sudo apt-get install wget zip unzip python2.7 python-pip -y
            node --version

      - run:
          name: change Directory
          command: |
            cd webapp
            ls -ax

      - run:
          name: update-npm
          command: |
            cd webapp
            npm install

      - run:
          name: start server
          command: |
            cd webapp
            node server.js
            npm start

      - run:
          name: test
          command: npm test